export const TOPIC_MAPPING: Record<string, string[]> = {
  "5": [
    "Phân số thập phân và hỗn số",
    "Số thập phân và các phép toán",
    "Diện tích hình tam giác, hình thang",
    "Chu vi và diện tích hình tròn",
    "Hình hộp chữ nhật, hình lập phương",
    "Hình trụ, hình cầu",
    "Đo thể tích và chuyển đổi đơn vị",
    "Toán chuyển động đều",
    "Giải toán tỉ số phần trăm",
    "Ôn tập"
  ],
  "6": [
    "Tập hợp số tự nhiên",
    "Tính chất chia hết và ước số",
    "Tập hợp số nguyên và phép tính",
    "Phân số bằng nhau và rút gọn",
    "Các phép tính với số thập phân",
    "Hình vuông, tam giác đều, lục giác đều",
    "Hình chữ nhật, hình thoi, hình bình hành",
    "Hình có trục đối xứng",
    "Hình có tâm đối xứng",
    "Điểm, đường thẳng, đoạn thẳng",
    "Trung điểm của đoạn thẳng",
    "Góc và số đo góc",
    "Ôn tập"
  ],
  "7": [
    "Tập hợp số hữu tỉ",
    "Căn bậc hai số học và số thực",
    "Tỉ lệ thức và tính chất dãy tỉ số bằng nhau",
    "Đại lượng tỉ lệ thuận, tỉ lệ nghịch",
    "Biểu thức đại số",
    "Đa thức một biến và nghiệm của đa thức",
    "Hai góc kề bù, đối đỉnh",
    "Dấu hiệu hai đường thẳng song song",
    "Tổng các góc trong một tam giác",
    "Tam giác bằng nhau (c.c.c, c.g.c, g.c.g)",
    "Tam giác cân và định lý Pythagoras",
    "Làm quen với xác suất của biến cố ngẫu nhiên",
    "Ôn tập"
  ],
  "8": [
    "Đơn thức và đa thức nhiều biến",
    "Các phép tính với đa thức",
    "Hằng đẳng thức đáng nhớ",
    "Khái niệm phân thức",
    "Các phép toán cộng, trừ, nhân, chia phân thức",
    "Khái niệm hàm số",
    "Hàm số bậc nhất y = ax + b",
    "Hệ số góc của đường thẳng",
    "Cách giải phương trình bậc nhất một ẩn",
    "Giải bài toán bằng cách lập phương trình",
    "Định lý Thalès thuận và đảo",
    "Đường trung bình của tam giác",
    "Các trường hợp đồng dạng của tam giác",
    "Tam giác vuông đồng dạng",
    "Hình chóp tam giác đều",
    "Hình chóp tứ giác đều",
    "Ôn tập"
  ],
  "9": [
    "Phương trình bậc nhất hai ẩn",
    "Hệ hai phương trình bậc nhất hai ẩn",
    "Hàm số y = ax^2 (a khác 0)",
    "Đồ thị hàm số bậc hai đơn giản",
    "Công thức nghiệm phương trình bậc hai",
    "Định lý Viète và ứng dụng",
    "Tỉ số lượng giác của góc nhọn",
    "Hệ thức giữa cạnh và góc",
    "Sự xác định đường tròn và vị trí tương đối",
    "Góc với đường tròn (Góc nội tiếp, góc ở tâm)",
    "Hình trụ",
    "Hình nón",
    "Hình cầu",
    "Ôn tập"
  ],
  "chuyen_cap": [
    "Rút gọn biểu thức chứa căn và các bài toán phụ",
    "Hệ phương trình bậc nhất hai ẩn & Hệ phương trình đối xứng",
    "Phương trình bậc hai, Tương giao Parabol (P) và Đường thẳng (d)",
    "Định lý Viète và các bài toán thực tế nâng cao",
    "Giải bài toán bằng cách lập phương trình, hệ phương trình",
    "Hình học đường tròn, Tiếp tuyến, Tứ giác nội tiếp & Điểm cố định",
    "Bất đẳng thức & Cực trị đại số (Min - Max)",
    "Phương trình vô tỉ và phương trình quy về bậc hai",
    "Toán thực tế liên môn (Vật lý, Hóa học, Tài chính, Tối ưu)",
    "Ôn tập"
  ]
};

export const GRADES = [
  { label: 'Lớp 5', value: '5' },
  { label: 'Lớp 6', value: '6' },
  { label: 'Lớp 7', value: '7' },
  { label: 'Lớp 8', value: '8' },
  { label: 'Lớp 9', value: '9' },
  { label: 'Chuyển cấp', value: 'chuyen_cap' }
];
