name: Deploy toan6789.vn to Dokku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy Backend to Dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@${{ secrets.VPS_HOST }}:22/toan6789-backend'
          ssh_private_key: ${{ secrets.VPS_SSH_KEY }}
          git_push_flags: '--force'
          subtree_path: 'backend'

      - name: Deploy Frontend to Dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@${{ secrets.VPS_HOST }}:22/toan6789-frontend'
          ssh_private_key: ${{ secrets.VPS_SSH_KEY }}
          git_push_flags: '--force'
          subtree_path: 'frontend'
